# **Курс "Програмування на мові Python"**

## **Практичне зайняття №9**

### Тема: "Робота з функціями. Локальні та глобальні змінні"

### **Завдання 1 (3 бали)**

**Підрахувати визначник матриці, використовуючи правило перестановок.**

Функція random_matrix() призначена для створення квадратної матриці випадкових чисел. Її змінювати непотрібно.

Приклад використання методу permutations() для створення списку перестановок також подається у комірці з кодом.

1) Створити 3 функції: функцію створення списку перестановок, функцію підрахунку добутків та функцію підрахунку загальної суми.

2) Кожна функція має супроводжуватись рядком документації, що буде коротко описувати її призначення.

3) Розмірність квадратної матриці має вводитись користувачем з клавіатури. Підрахунки виконувати лише в тому разі, якщо користувач введе ціле додатне число.

4) Загальний результат повинен підраховуватись за допомогою композиції функцій.

За бажанням можна перевірити правильність роботи програми за допомогою функції np.linalg.det(a).

In [8]:
import numpy as np
import itertools

def random_matrix(dim):
    """
    The function generates dim x dim array of integers
    between 0 and 10.
    """
    matrix = np.random.randint(10, size = (dim, dim))
    return matrix

def check_n():
    """ 
    The function to enter the correct size of matrix
    """
    a=True
    while a:
        try:
            n=int(input("Please, enter size your matrix: "))
            if n<1:
                print("You entered a number less than 1, please try again ")
            else: 
                a=False
        except ValueError:
            print("You entered not integer number, please try again")
        except Exception:
            print("Sorry, an unknown error has occurred, please try again")
    return n
n=check_n()
matrix=random_matrix(n)
print("Your matrix: \n", matrix)
def permutations(x):
    """
    The function make permutations of matrix elements
    """
    per = list(itertools.permutations([str(i) for i in range(1,x+1)], x))
    return per
def dob(inv):
    """
    The function counts the multiplication of elements
    """
    global matrix
    mult=[]
    for a in inv:
        part,num=1,0
        for k in range(len(a)):
            for i in range(k+1):
                if a[i]>a[k]:
                    num+=1
        for i in range(len(a)):
            part = part*int(matrix[i][int(a[i])-1])
        mult.append(pow(-1,num)*part)
    return mult
def sum(lis):
    """
    The function counts the sum of multiplications elements
    """
    s=0
    for i in lis:
        s+=i
    return s
print("Determinant of your matrix: ", sum(dob(permutations(n))))
print("Determinant of your matrix by using library numpy: ", round(np.linalg.det(matrix)))

Your matrix: 
 [[9 2 0 7 8 4 5 2 3 7]
 [0 7 8 9 6 7 7 6 5 0]
 [2 8 4 5 5 5 3 2 5 1]
 [3 5 8 5 7 4 5 7 6 5]
 [5 3 4 7 5 1 0 9 2 6]
 [7 0 5 6 2 6 1 5 5 5]
 [1 8 6 0 7 8 6 6 2 7]
 [4 7 5 0 0 2 6 9 1 5]
 [8 7 0 9 5 5 3 8 2 2]
 [0 4 6 9 5 6 1 8 5 8]]
Determinant of your matrix:  273225456
Determinant of your matrix by using library numpy:  273225456
